#include "shared.h"
#include <xnes.h>

static int overscan = true;
static int autocrop = 0;
static int palette = 0;
static bool slowFrame = false;

static struct xnes_ctx_t *nes;
static rg_app_t *app;
static rg_surface_t *updates[2];
static rg_surface_t *currentUpdate;

static const char *SETTING_AUTOCROP = "autocrop";
static const char *SETTING_OVERSCAN = "overscan";
static const char *SETTING_PALETTE = "palette";
static const char *SETTING_SPRITELIMIT = "spritelimit";

static void event_handler(int event, void *arg)
{
    if (event == RG_EVENT_REDRAW)
    {
        if (nes)
        {
            // redraw if needed
        }
    }
}

static bool screenshot_handler(const char *filename, int width, int height)
{
    return rg_surface_save_image_file(currentUpdate, filename, width, height);
}

static bool save_state_handler(const char *filename)
{
    // not implemented for xnes yet
    return true;
}

static bool load_state_handler(const char *filename)
{
    // not implemented for xnes yet
    return true;
}

static bool reset_handler(bool hard)
{
    if (nes) xnes_reset(nes);
    return true;
}

static void build_palette(int n)
{
    // placeholder palette
    for (int i = 0; i < 64; i++)
    {
        // just use the palette generated by xnes, which is probably RGBA or similar
        // for now we'll just let xnes run.
    }
}

static rg_gui_event_t overscan_update_cb(rg_gui_option_t *option, rg_gui_event_t event)
{
    return RG_DIALOG_VOID;
}

static void options_handler(rg_gui_option_t *dest)
{
    *dest++ = (rg_gui_option_t){0, _("Overscan"),     "-", RG_DIALOG_FLAG_NORMAL, &overscan_update_cb};
    *dest++ = (rg_gui_option_t)RG_DIALOG_END;
}

static void blit_screen()
{
    slowFrame = !rg_display_sync(false);
    currentUpdate->width = 256;
    currentUpdate->height = 240;
    
    // copy front buffer
    if (nes) {
        uint8_t *front = nes->ppu.front;
        uint16_t *dest = (uint16_t*)currentUpdate->data;
        for (int i = 0; i < 256 * 240; i++) {
            uint32_t color = nes->palette[front[i] & 0x3f];
            dest[i] = ((color >> 8) & 0xF800) | ((color >> 5) & 0x07E0) | ((color >> 3) & 0x001F);
        }
    }
    
    rg_display_submit(currentUpdate, 0);
}

void nes_main(void)
{
    const rg_handlers_t handlers = {
        .loadState = &load_state_handler,
        .saveState = &save_state_handler,
        .reset = &reset_handler,
        .event = &event_handler,
        .screenshot = &screenshot_handler,
        .options = &options_handler,
    };

    app = rg_system_reinit(0, &handlers, NULL);

    updates[0] = rg_surface_create(256, 240, RG_PIXEL_565, MEM_FAST);
    updates[1] = rg_surface_create(256, 240, RG_PIXEL_565, MEM_FAST);
    currentUpdate = updates[0];

    size_t size;
    void *data = rg_storage_read_file(app->romPath, &size);
    if (!data)
        RG_PANIC("ROM load failed.");

    nes = xnes_ctx_alloc(data, size);
    free(data);
    if (!nes)
        RG_PANIC("Init failed.");

    rg_system_set_tick_rate(60);

    while (true)
    {
        uint32_t joystick = rg_input_read_gamepad();
        if (joystick & (RG_KEY_MENU|RG_KEY_OPTION))
            rg_gui_game_menu();

        int64_t startTime = rg_system_timer();
        
        nes->ctl.p1_state = 0;
        if (joystick & RG_KEY_START)  nes->ctl.p1_state |= (1 << 3);
        if (joystick & RG_KEY_SELECT) nes->ctl.p1_state |= (1 << 2);
        if (joystick & RG_KEY_UP)     nes->ctl.p1_state |= (1 << 4);
        if (joystick & RG_KEY_RIGHT)  nes->ctl.p1_state |= (1 << 7);
        if (joystick & RG_KEY_DOWN)   nes->ctl.p1_state |= (1 << 5);
        if (joystick & RG_KEY_LEFT)   nes->ctl.p1_state |= (1 << 6);
        if (joystick & RG_KEY_A)      nes->ctl.p1_state |= (1 << 0);
        if (joystick & RG_KEY_B)      nes->ctl.p1_state |= (1 << 1);

        xnes_step_frame(nes);

        currentUpdate = updates[currentUpdate == updates[0]];
        blit_screen();

        rg_system_tick(rg_system_timer() - startTime);

        int frameTime = 1000000 / 60;
        int elapsed = rg_system_timer() - startTime;
        if (elapsed < frameTime)
            rg_system_sleep((frameTime - elapsed) / 1000);
    }
}
